spring:
  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

cookie:
  secure: false

logging:
  level:
    root: INFO
    com.jonathan.ecommerce: DEBUG
