spring:
  flyway:
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: false
    show-sql: false

cookie:
  secure: true

logging:
  level:
    root: WARN
    com.jonathan.ecommerce: INFO
