-- =============================================================
-- V1__initial_schema.sql
-- Baseline schema — estado real de la base antes de las migraciones V2+
-- Generado desde pg_dump y validado contra las entidades JPA
-- =============================================================

-- -------------------------------------------------------------
-- USERS
-- -------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,

    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'))
);

-- -------------------------------------------------------------
-- TOKENS  (blacklist JWT legacy — anterior a Redis)
-- -------------------------------------------------------------
CREATE TABLE tokens (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expired BOOLEAN NOT NULL,
    revoked BOOLEAN NOT NULL,
    user_id BIGINT  NOT NULL,
    token   TEXT    NOT NULL,

    CONSTRAINT tokens_token_key UNIQUE (token),
    CONSTRAINT fk_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_tokens_token ON tokens (token);

-- -------------------------------------------------------------
-- CATEGORY
-- -------------------------------------------------------------
CREATE TABLE category (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    parent_category_id BIGINT,

    CONSTRAINT category_name_key UNIQUE (name),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id) REFERENCES category (id)
);

-- -------------------------------------------------------------
-- PRODUCTS
-- -------------------------------------------------------------
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(255),
    price       NUMERIC(38, 2) NOT NULL,
    status      VARCHAR(255)   NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    category_id BIGINT,

    CONSTRAINT products_name_key UNIQUE (name),
    CONSTRAINT products_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK')),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- -------------------------------------------------------------
-- INVENTORY
-- (version incluida — existía en la base aunque esté comentada en la entity)
-- -------------------------------------------------------------
CREATE TABLE inventory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT      NOT NULL,
    quantity         INTEGER     NOT NULL DEFAULT 0,
    inventory_status VARCHAR(255) NOT NULL,
    manual_disabled  BOOLEAN     NOT NULL DEFAULT FALSE,
    version          BIGINT,

    CONSTRAINT inventory_product_id_key UNIQUE (product_id),
    CONSTRAINT inventory_inventory_status_check CHECK (inventory_status IN ('IN_STOCK', 'OUT_OF_STOCK')),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- -------------------------------------------------------------
-- INVENTORY_MOVEMENT
-- -------------------------------------------------------------
CREATE TABLE inventory_movement (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id  BIGINT,
    movement_type VARCHAR(255) NOT NULL,
    quantity      INTEGER      NOT NULL,
    date          TIMESTAMP WITH TIME ZONE NOT NULL,
    reason        VARCHAR(255),

    CONSTRAINT inventory_movement_movement_type_check CHECK (movement_type IN ('IN', 'OUT')),
    CONSTRAINT fk_movement_inventory FOREIGN KEY (inventory_id) REFERENCES inventory (id)
);

-- -------------------------------------------------------------
-- CART
-- -------------------------------------------------------------
CREATE TABLE cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    cart_status VARCHAR(255) NOT NULL,

    CONSTRAINT uk_cart_user UNIQUE (user_id),
    CONSTRAINT cart_cart_status_check CHECK (cart_status IN ('ACTIVE', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- -------------------------------------------------------------
-- CART_ITEM  (tabla legacy — generada por Hibernate en etapa inicial)
-- -------------------------------------------------------------
CREATE TABLE cart_item (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity  INTEGER,
    sub_total NUMERIC(38, 2),
    unit_price NUMERIC(38, 2),
    cart      BIGINT,
    product   BIGINT,

    CONSTRAINT fk_cart_item_legacy_cart    FOREIGN KEY (cart)    REFERENCES cart (id),
    CONSTRAINT fk_cart_item_legacy_product FOREIGN KEY (product) REFERENCES products (id)
);

-- -------------------------------------------------------------
-- CART_ITEMS  (tabla actual)
-- -------------------------------------------------------------
CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT,
    product_id BIGINT,
    quantity   INTEGER,
    unit_price NUMERIC(38, 2),

    CONSTRAINT fk_cart_items_cart    FOREIGN KEY (cart_id)    REFERENCES cart (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- -------------------------------------------------------------
-- PAYMENT
-- (se crea antes de orders por la dependencia circular)
-- -------------------------------------------------------------
CREATE TABLE payment (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                 BIGINT,
    stripe_payment_intent_id VARCHAR(255),
    amount                   NUMERIC(19, 2),
    payment_status           VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    updated_at               TIMESTAMP WITH TIME ZONE,

    CONSTRAINT payment_payment_status_check CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

-- -------------------------------------------------------------
-- ORDERS
-- -------------------------------------------------------------
CREATE TABLE orders (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    order_status      VARCHAR(255) NOT NULL,
    total_amount      NUMERIC(38, 2),
    stripe_payment_id VARCHAR(255),
    user_id           BIGINT NOT NULL,
    payment_id        BIGINT,

    CONSTRAINT ukmk3082kek6a9g7y8gkk4804hj UNIQUE (stripe_payment_id),
    CONSTRAINT ukhaujdjk1ohmeixjhnhslchrp1 UNIQUE (payment_id),
    CONSTRAINT fk_order_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_order_payment FOREIGN KEY (payment_id) REFERENCES payment (id)
);

-- FK inversa payment → orders
ALTER TABLE payment
    ADD CONSTRAINT ukmf7n8wo2rwrxsd6f3t9ub2mep UNIQUE (order_id);

ALTER TABLE payment
    ADD CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders (id);

-- -------------------------------------------------------------
-- ORDER_ITEMS
-- -------------------------------------------------------------
CREATE TABLE order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity          INTEGER        NOT NULL,
    price_at_purchase NUMERIC(38, 2) NOT NULL,
    order_id          BIGINT         NOT NULL,
    product_id        BIGINT         NOT NULL,

    CONSTRAINT fk_order_item_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- -------------------------------------------------------------
-- PAYMENT_ATTEMPT
-- -------------------------------------------------------------
CREATE TABLE payment_attempt (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id     BIGINT,
    attempt_number INTEGER      NOT NULL,
    status         VARCHAR(255),
    error_message  VARCHAR(255),
    transaction_id VARCHAR(255),
    attempted_at   TIMESTAMP WITH TIME ZONE,

    CONSTRAINT payment_attempt_status_check CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING')),
    CONSTRAINT fk_attempt_payment FOREIGN KEY (payment_id) REFERENCES payment (id)
);

-- -------------------------------------------------------------
-- REFRESH_TOKEN
-- (V3 convierte family_id de VARCHAR a UUID y añade user_agent, ip_address, created_at)
-- -------------------------------------------------------------
CREATE TABLE refresh_token (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash             VARCHAR(255) NOT NULL,
    user_id                BIGINT,
    expires_at             TIMESTAMP WITH TIME ZONE,
    revoked                BOOLEAN      NOT NULL DEFAULT FALSE,
    replaced_by_token      VARCHAR(255),
    replaced_by_token_hash VARCHAR(255),
    family_id              VARCHAR(36),

    CONSTRAINT refresh_token_token_hash_key UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- -------------------------------------------------------------
-- FAILED_EMAILS
-- (product_name existía en la base real aunque no está en la entity actual)
-- (V7 añade email_type con IF NOT EXISTS — se incluye ya en el baseline)
-- -------------------------------------------------------------
CREATE TABLE failed_emails (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient     VARCHAR(255) NOT NULL,
    product_name  VARCHAR(255) NOT NULL,
    email_type    VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
    payload       TEXT,
    error_message TEXT,
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    retry_count   INTEGER,
    status        VARCHAR(255),

    CONSTRAINT failed_emails_status_check CHECK (status IN ('PENDING', 'RETRYING', 'SENT', 'FAILED'))
);

-- -------------------------------------------------------------
-- FAILED_PAYMENT_EVENTS
-- -------------------------------------------------------------
CREATE TABLE failed_payment_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT   NOT NULL,
    attempt_number    INTEGER  NOT NULL,
    error_message     TEXT,
    failed_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    notification_sent BOOLEAN  NOT NULL DEFAULT FALSE
);

-- -------------------------------------------------------------
-- STOCK_NOTIFICATION
-- -------------------------------------------------------------
CREATE TABLE stock_notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    product_id  BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE,
    is_notified BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_stock_notif_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_stock_notif_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- =============================================================
-- Nota: las siguientes tablas fueron creadas por migraciones
-- posteriores y NO se incluyen en este baseline:
--   - password_reset_token  → V4
--   - outbox_event          → V5
--   - processed_event       → V6
--
-- Cambios aplicados post-baseline:
--   V2 → índices sobre users(email) y orders(user_id, created_at)
--   V3 → family_id a UUID, uk_refresh_token_family_id, user_agent, ip_address, created_at
--   V7 → email_type en failed_emails (IF NOT EXISTS — ya presente en baseline)
-- =============================================================
